-- tools/manifest.lua -- regenerates manifest.lua, the list of files
-- install.lua installs, with each file's size and checksum (so updates
-- download only what changed, and every download is verified).
--
--   lua tools/manifest.lua          (from the repository root; run it
--                                    before committing -- the test suite
--                                    fails while it is out of date)
--
-- Files: whatever git tracks (or would track) under ocui/, apps/, boot/.
-- Where they go: ocui/X -> /lib/ocui/X, apps/X -> /usr/bin/X,
-- boot/X -> /boot/X.

local root = (arg and arg[0] or ""):match("^(.*)[/\\]tools[/\\]manifest%.lua$") or "."

local M = {}

-- 32-bit djb2 over the bytes, as 8 hex digits -- install.lua has the same
-- function. Exact in both Lua 5.2 (doubles) and 5.3 (integers).
function M.checksum(s)
  local h = 5381
  for i = 1, #s, 4096 do
    local bytes = { s:byte(i, math.min(i + 4095, #s)) }
    for j = 1, #bytes do h = (h * 33 + bytes[j]) % 4294967296 end
  end
  return string.format("%08x", h)
end

-- Raw GitHub serves the committed (LF) text; a Windows checkout may have
-- CRLF.
function M.normalize(text) return (text:gsub("\r\n", "\n")) end

function M.target(path)
  local rest = path:match("^ocui/(.+)$")
  if rest then return "/lib/ocui/" .. rest end
  rest = path:match("^apps/(.+)$")
  if rest then return "/usr/bin/" .. rest end
  rest = path:match("^boot/(.+)$")
  if rest then return "/boot/" .. rest end
  return nil
end

function M.files(base)
  base = base or root
  local list = {}
  local git = assert(io.popen('git -C "' .. base .. '" ls-files --cached --others --exclude-standard ocui apps boot'))
  for path in git:lines() do
    if M.target(path) then list[#list + 1] = path end
  end
  git:close()
  table.sort(list)
  return list
end

function M.entries(base)
  base = base or root
  local entries = {}
  for _, path in ipairs(M.files(base)) do
    local f = assert(io.open(base .. "/" .. path, "rb"))
    local text = M.normalize(f:read("a"))
    f:close()
    -- a NUL byte makes git treat the file as binary: it would then keep
    -- CRLF line ends and the checksum here would not match what GitHub
    -- serves (write "\0" in Lua source instead)
    assert(not text:find("\0", 1, true), path .. " contains a NUL byte")
    entries[#entries + 1] = { path, M.target(path), #text, M.checksum(text) }
  end
  return entries
end

function M.render(entries)
  local lines = {
    "-- manifest.lua -- generated by tools/manifest.lua; do not edit by hand.",
    "-- { file in the repository, install path, size, checksum }",
    "return {",
  }
  for _, e in ipairs(entries) do
    lines[#lines + 1] = string.format('  { %q, %q, %d, %q },', e[1], e[2], e[3], e[4])
  end
  lines[#lines + 1] = "}"
  return table.concat(lines, "\n") .. "\n"
end

-- Run as a program: write manifest.lua.
if arg and arg[0] and arg[0]:match("tools[/\\]manifest%.lua$") then
  local text = M.render(M.entries())
  local f = assert(io.open(root .. "/manifest.lua", "wb"))
  f:write(text)
  f:close()
  local n = select(2, text:gsub("\n  {", ""))
  print(string.format("manifest.lua: %d files", n))
end

return M
